.PHONY: clean All

All:
	@echo "----------Building project:[ 10-SectionChallenge - Debug ]----------"
	@cd "10-SectionChallenge" && "$(MAKE)" -f  "10-SectionChallenge.mk"
clean:
	@echo "----------Cleaning project:[ 10-SectionChallenge - Debug ]----------"
	@cd "10-SectionChallenge" && "$(MAKE)" -f  "10-SectionChallenge.mk" clean
