.PHONY: clean All

All:
	@echo "----------Building project:[ 6-CompilerWarnings - Debug ]----------"
	@cd "6-CompilerWarnings" && "$(MAKE)" -f  "6-CompilerWarnings.mk"
clean:
	@echo "----------Cleaning project:[ 6-CompilerWarnings - Debug ]----------"
	@cd "6-CompilerWarnings" && "$(MAKE)" -f  "6-CompilerWarnings.mk" clean
