.PHONY: clean All

All:
	@echo "----------Building project:[ WritingOurFirstProgram - Debug ]----------"
	@cd "WritingOurFirstProgram" && "$(MAKE)" -f  "WritingOurFirstProgram.mk"
clean:
	@echo "----------Cleaning project:[ WritingOurFirstProgram - Debug ]----------"
	@cd "WritingOurFirstProgram" && "$(MAKE)" -f  "WritingOurFirstProgram.mk" clean
